<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ReservationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \App\Models\Reservation::insert([
            [
                'user_id' => 1,
                'room_id' => 1,
                'book_code' => 'Book20200901048009',
                'guest_count' => 2,
                'check_in' => '2020-01-11 20:35:00',
                'check_out' => '2020-01-12 20:35:00',
                'reservation_status' => 'success',
                'validation' => 'success',
                'note' => 's simply dummy text of the printing and types',
            ],
            [
                'user_id' => 2,
                'room_id' => 1,
                'book_code' => 'Book20201902048009',
                'guest_count' => 2,
                'check_in' => '2020-02-11 20:35:00',
                'check_out' => '2020-02-12 20:35:00',
                'reservation_status' => 'success',
                'validation' => 'success',
                'note' => 'en an unknown printer took',
            ],
            [
                'user_id' => 2,
                'room_id' => 2,
                'book_code' => 'Book20202802048009',
                'guest_count' => 2,
                'check_in' => '2020-02-28 20:35:00',
                'check_out' => '2020-02-29 20:35:00',
                'reservation_status' => 'success',
                'validation' => 'success',
                'note' => 'and scrambled it to',
            ],
            [
                'user_id' => 3,
                'room_id' => 2,
                'book_code' => 'Book20200103048009',
                'guest_count' => 2,
                'check_in' => '2020-03-01 20:35:00',
                'check_out' => '2020-03-02 20:35:00',
                'reservation_status' => 'success',
                'validation' => 'success',
                'note' => 'and scrambled it to',
            ],
            [
                'user_id' => 4,
                'room_id' => 2,
                'book_code' => 'Book20200303048009',
                'guest_count' => 2,
                'check_in' => '2020-03-03 20:35:00',
                'check_out' => '2020-03-04 20:35:00',
                'reservation_status' => 'success',
                'validation' => 'success',
                'note' => 'and scrambled it to',
            ],
            [
                'user_id' => 5,
                'room_id' => 1,
                'book_code' => 'Book20200603048009',
                'guest_count' => 2,
                'check_in' => '2020-03-06 20:35:00',
                'check_out' => '2020-03-07 20:35:00',
                'reservation_status' => 'success',
                'validation' => 'success',
                'note' => 'and scrambled it to',
            ],
            [
                'user_id' => 5,
                'room_id' => 3,
                'book_code' => 'Book20200604048009',
                'guest_count' => 1,
                'check_in' => '2020-04-06 20:35:00',
                'check_out' => '2020-04-07 20:35:00',
                'reservation_status' => 'success',
                'validation' => 'success',
                'note' => 'and scrambled it to',
            ],
            [
                'user_id' => 6,
                'room_id' => 3,
                'book_code' => 'Book20200605048009',
                'guest_count' => 1,
                'check_in' => '2020-05-06 20:35:00',
                'check_out' => '2020-05-07 20:35:00',
                'reservation_status' => 'success',
                'validation' => 'success',
                'note' => 'and scrambled it to',
            ],
            [
                'user_id' => 7,
                'room_id' => 3,
                'book_code' => 'Book20200606048009',
                'guest_count' => 1,
                'check_in' => '2020-06-06 20:35:00',
                'check_out' => '2020-06-07 20:35:00',
                'reservation_status' => 'success',
                'validation' => 'success',
                'note' => 'and scrambled it to',
            ],
            [
                'user_id' => 7,
                'room_id' => 3,
                'book_code' => 'Book20200607048009',
                'guest_count' => 1,
                'check_in' => '2020-07-06 20:35:00',
                'check_out' => '2020-07-07 20:35:00',
                'reservation_status' => 'success',
                'validation' => 'success',
                'note' => 'and scrambled it to',
            ],
            [
                'user_id' => 8,
                'room_id' => 1,
                'book_code' => 'Book20200608048009',
                'guest_count' => 2,
                'check_in' => '2020-08-06 20:35:00',
                'check_out' => '2020-08-07 20:35:00',
                'reservation_status' => 'success',
                'validation' => 'success',
                'note' => 'and scrambled it to',
            ],
            [
                'user_id' => 1,
                'room_id' => 1,
                'book_code' => 'Book20201808048009',
                'guest_count' => 2,
                'check_in' => '2020-08-18 20:35:00',
                'check_out' => '2020-08-19 20:35:00',
                'reservation_status' => 'success',
                'validation' => 'success',
                'note' => 'and scrambled it to',
            ],
            [
                'user_id' => 1,
                'room_id' => 2,
                'book_code' => 'Book20201809048009',
                'guest_count' => 2,
                'check_in' => '2020-09-18 20:35:00',
                'check_out' => '2020-09-19 20:35:00',
                'reservation_status' => 'success',
                'validation' => 'success',
                'note' => 'and scrambled it to',
            ],
            [
                'user_id' => 9,
                'room_id' => 3,
                'book_code' => 'Book20201810048009',
                'guest_count' => 1,
                'check_in' => '2020-10-18 20:35:00',
                'check_out' => '2020-10-19 20:35:00',
                'reservation_status' => 'success',
                'validation' => 'success',
                'note' => 'and scrambled it to',
            ],
            [
                'user_id' => 3,
                'room_id' => 3,
                'book_code' => 'Book20201811048009',
                'guest_count' => 1,
                'check_in' => '2020-11-18 20:35:00',
                'check_out' => '2020-11-19 20:35:00',
                'reservation_status' => 'success',
                'validation' => 'success',
                'note' => 'and scrambled it to',
            ],
            [
                'user_id' => 3,
                'room_id' => 3,
                'book_code' => 'Book20201812048009',
                'guest_count' => 1,
                'check_in' => '2020-12-18 20:35:00',
                'check_out' => '2020-12-19 20:35:00',
                'reservation_status' => 'success',
                'validation' => 'success',
                'note' => 'and scrambled it to',
            ],
            [
                'user_id' => 5,
                'room_id' => 1,
                'book_code' => 'Book20201814048009',
                'guest_count' => 2,
                'check_in' => '2020-12-20 20:35:00',
                'check_out' => '2020-12-21 20:35:00',
                'reservation_status' => 'success',
                'validation' => 'success',
                'note' => 'and scrambled it to',
            ],
        ]);
    }
}
