@extends('layouts.landing-app')
@section('landing-content')
    @include('component.header')
    @include('component.banner')
    @include('component.roomlist')
    @include('component.facilities')
    @include('component.about')
    @include('component.footer')
@endsection